In [1]:
import pandas as pd

In [2]:
ages = pd.Series([22, 25, 30, 28])

print(ages)

0    22
1    25
2    30
3    28
dtype: int64

In [3]:
Data = {
    "Name" : ["Salman" , "Zeeshan" , "Mahnoor" , "Zainab"],
    "Age" : [20 , 23 , 21, 20],
    "gender" : ["Male" , "Male" , "Female" , "Female"],
    "Salary" : [50000000 , 3000000 , 4000000 , 200000] 
}

df = pd.DataFrame(Data)
print(df)

      Name  Age  gender    Salary
0   Salman   20    Male  50000000
1  Zeeshan   23    Male   3000000
2  Mahnoor   21  Female   4000000
3   Zainab   20  Female    200000

In [4]:
print(df.columns)

Index(['Name', 'Age', 'gender', 'Salary'], dtype='str')

In [5]:
print(df.head(2))

      Name  Age gender    Salary
0   Salman   20   Male  50000000
1  Zeeshan   23   Male   3000000

In [6]:
print(df.tail(2))

      Name  Age  gender   Salary
2  Mahnoor   21  Female  4000000
3   Zainab   20  Female   200000

In [7]:
print(df.shape)

(4, 4)

In [8]:
print(df.dtypes)

Name        str
Age       int64
gender      str
Salary    int64
dtype: object

In [9]:
print(df.describe)

<bound method NDFrame.describe of       Name  Age  gender    Salary
0   Salman   20    Male  50000000
1  Zeeshan   23    Male   3000000
2  Mahnoor   21  Female   4000000
3   Zainab   20  Female    200000>

In [10]:
print(df[["Name" , "Age"]])

      Name  Age
0   Salman   20
1  Zeeshan   23
2  Mahnoor   21
3   Zainab   20

In [11]:
print(df.loc[0])   #loc function

Name        Salman
Age             20
gender        Male
Salary    50000000
Name: 0, dtype: object

In [12]:
print(df.loc[1])

Name      Zeeshan
Age            23
gender       Male
Salary    3000000
Name: 1, dtype: object

In [13]:
print(df.iloc[0])

Name        Salman
Age             20
gender        Male
Salary    50000000
Name: 0, dtype: object

In [14]:
print(df[df["Salary"] > 30000000])

     Name  Age gender    Salary
0  Salman   20   Male  50000000

In [15]:
print(df[(df["Age"] > 25) & (df["Salary"] > 600)])

Empty DataFrame
Columns: [Name, Age, gender, Salary]
Index: []

In [16]:
df["Salary after bonus"] = df["Salary"] * 34

In [17]:
print(df)

      Name  Age  gender    Salary  Salary after bonus
0   Salman   20    Male  50000000          1700000000
1  Zeeshan   23    Male   3000000           102000000
2  Mahnoor   21  Female   4000000           136000000
3   Zainab   20  Female    200000             6800000

In [18]:
df["Age group"] = df["Age"].apply(lambda x : "Adult" if x > 20 else "Young")
print(df)

      Name  Age  gender    Salary  Salary after bonus Age group
0   Salman   20    Male  50000000          1700000000     Young
1  Zeeshan   23    Male   3000000           102000000     Adult
2  Mahnoor   21  Female   4000000           136000000     Adult
3   Zainab   20  Female    200000             6800000     Young

In [19]:
X = df[["Age" , "Name"]]
Y = df["Salary"]
print(X)

   Age     Name
0   20   Salman
1   23  Zeeshan
2   21  Mahnoor
3   20   Zainab

In [20]:
print(Y)

0    50000000
1     3000000
2     4000000
3      200000
Name: Salary, dtype: int64

In [21]:
df = pd.read_csv("industry.csv")

In [22]:
df.head()

                        Industry
0             Accounting/Finance
1   Advertising/Public Relations
2             Aerospace/Aviation
3  Arts/Entertainment/Publishing
4                     Automotive

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Industry  43 non-null     str
dtypes: str(1)
memory usage: 476.0 bytes

In [24]:
df.describe()

                  Industry
count                   43
unique                  43
top     Accounting/Finance
freq                     1

In [25]:
df.tail()

                    Industry
38             Skilled Labor
39                Technology
40        Telecommunications
41  Transportation/Logistics
42                     Other

In [26]:
import numpy as np

data = {
    "Name": ["Ali", "Sara", "Omar", "Maha", "Ali", "Khalid", "Noor"],
    "Age": [25, 30, np.nan, 28, 25, 40, 120],
    "Gender": ["Male", "Female", "male", "Female", "Male", np.nan, "Female"],
    "Salary": [500, 700, 650, np.nan, 500, 900, 10000],
    "Department": ["IT", "Finance", "it", "HR", "IT", "Finance", "HR"],
    "Purchased": ["Yes", "No", "Yes", "No", "Yes", "Yes", "No"]
}

df = pd.DataFrame(data)
df

     Name    Age  Gender   Salary Department Purchased
0     Ali   25.0    Male    500.0         IT       Yes
1    Sara   30.0  Female    700.0    Finance        No
2    Omar    NaN    male    650.0         it       Yes
3    Maha   28.0  Female      NaN         HR        No
4     Ali   25.0    Male    500.0         IT       Yes
5  Khalid   40.0     NaN    900.0    Finance       Yes
6    Noor  120.0  Female  10000.0         HR        No

In [27]:
df.isna().sum()

Name          0
Age           1
Gender        1
Salary        1
Department    0
Purchased     0
dtype: int64

In [28]:
df.isna().sum() * 100

Name            0
Age           100
Gender        100
Salary        100
Department      0
Purchased       0
dtype: int64

In [29]:
df_drop = df.dropna()

In [30]:
df_drop

   Name    Age  Gender   Salary Department Purchased
0   Ali   25.0    Male    500.0         IT       Yes
1  Sara   30.0  Female    700.0    Finance        No
4   Ali   25.0    Male    500.0         IT       Yes
6  Noor  120.0  Female  10000.0         HR        No

In [31]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [32]:
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

In [33]:
df

     Name         Age  Gender        Salary Department Purchased
0     Ali   25.000000    Male    500.000000         IT       Yes
1    Sara   30.000000  Female    700.000000    Finance        No
2    Omar   44.666667    male    650.000000         it       Yes
3    Maha   28.000000  Female   2208.333333         HR        No
4     Ali   25.000000    Male    500.000000         IT       Yes
5  Khalid   40.000000     NaN    900.000000    Finance       Yes
6    Noor  120.000000  Female  10000.000000         HR        No

In [34]:
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Salary"] = df["Salary"].fillna(df["Salary"].median())

In [35]:
df

     Name         Age  Gender        Salary Department Purchased
0     Ali   25.000000    Male    500.000000         IT       Yes
1    Sara   30.000000  Female    700.000000    Finance        No
2    Omar   44.666667    male    650.000000         it       Yes
3    Maha   28.000000  Female   2208.333333         HR        No
4     Ali   25.000000    Male    500.000000         IT       Yes
5  Khalid   40.000000     NaN    900.000000    Finance       Yes
6    Noor  120.000000  Female  10000.000000         HR        No

In [36]:
df["Gender"] = df["Gender"].fillna(df["Gender"].mode()[0])
df

     Name         Age  Gender        Salary Department Purchased
0     Ali   25.000000    Male    500.000000         IT       Yes
1    Sara   30.000000  Female    700.000000    Finance        No
2    Omar   44.666667    male    650.000000         it       Yes
3    Maha   28.000000  Female   2208.333333         HR        No
4     Ali   25.000000    Male    500.000000         IT       Yes
5  Khalid   40.000000  Female    900.000000    Finance       Yes
6    Noor  120.000000  Female  10000.000000         HR        No

In [37]:
df[df.duplicated()]

  Name   Age Gender  Salary Department Purchased
4  Ali  25.0   Male   500.0         IT       Yes

In [38]:
df = df.drop_duplicates()

In [39]:
df

     Name         Age  Gender        Salary Department Purchased
0     Ali   25.000000    Male    500.000000         IT       Yes
1    Sara   30.000000  Female    700.000000    Finance        No
2    Omar   44.666667    male    650.000000         it       Yes
3    Maha   28.000000  Female   2208.333333         HR        No
5  Khalid   40.000000  Female    900.000000    Finance       Yes
6    Noor  120.000000  Female  10000.000000         HR        No

In [40]:
df["Gender"].unique()

df["Gender"] = df["Gender"].str.title()

In [41]:
df["Gender"].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [42]:
df

     Name         Age  Gender        Salary Department Purchased
0     Ali   25.000000    Male    500.000000         IT       Yes
1    Sara   30.000000  Female    700.000000    Finance        No
2    Omar   44.666667    Male    650.000000         it       Yes
3    Maha   28.000000  Female   2208.333333         HR        No
5  Khalid   40.000000  Female    900.000000    Finance       Yes
6    Noor  120.000000  Female  10000.000000         HR        No

In [43]:
df["Department"] = df["Department"].str.upper()

df["Department"].unique()

<StringArray>
['IT', 'FINANCE', 'HR']
Length: 3, dtype: str

In [44]:
df["Salary"] = pd.to_numeric(df["Salary"])

In [45]:
df

     Name         Age  Gender        Salary Department Purchased
0     Ali   25.000000    Male    500.000000         IT       Yes
1    Sara   30.000000  Female    700.000000    FINANCE        No
2    Omar   44.666667    Male    650.000000         IT       Yes
3    Maha   28.000000  Female   2208.333333         HR        No
5  Khalid   40.000000  Female    900.000000    FINANCE       Yes
6    Noor  120.000000  Female  10000.000000         HR        No

In [46]:
import pandas as pd
import numpy as np

data = {
    "Well": ["W1", "W2", "W3", "W4", "W5", "W6", "W7", "W8"],
    "Area": ["South", "South", "North", "North", "East", "East", "South", "North"],
    "Category": ["A", "B", "A", "C", "B", "C", "A", "B"],
    "Oil_Rate": [1200, 950, 1100, 400, 700, 300, 1500, 850],
    "Water_Cut": [20, 35, 25, 70, 45, 80, 15, 40],
    "Deferment_Hours": [5, 12, 3, 30, 15, 40, 2, 9],
    "MTTR": [2.5, 6.0, 1.5, 15.0, 8.0, 20.0, 1.0, 5.5],
    "Status": ["Online", "Offline", "Online", "Offline", "Online", "Offline", "Online", "Online"]
}

df = pd.DataFrame(data)

df

  Well   Area Category  Oil_Rate  Water_Cut  Deferment_Hours  MTTR   Status
0   W1  South        A      1200         20                5   2.5   Online
1   W2  South        B       950         35               12   6.0  Offline
2   W3  North        A      1100         25                3   1.5   Online
3   W4  North        C       400         70               30  15.0  Offline
4   W5   East        B       700         45               15   8.0   Online
5   W6   East        C       300         80               40  20.0  Offline
6   W7  South        A      1500         15                2   1.0   Online
7   W8  North        B       850         40                9   5.5   Online

In [47]:
df.loc[0:3 , ["Well" , "Area" , "Oil_Rate"]]

  Well   Area  Oil_Rate
0   W1  South      1200
1   W2  South       950
2   W3  North      1100
3   W4  North       400

In [48]:
df.iloc[0:3 , 0:4]

  Well   Area Category  Oil_Rate
0   W1  South        A      1200
1   W2  South        B       950
2   W3  North        A      1100

In [49]:
df.at[1 , "Well"]

'W2'

In [50]:
df[df["Category"].isin(["South" , "North"])]

Empty DataFrame
Columns: [Well, Area, Category, Oil_Rate, Water_Cut, Deferment_Hours, MTTR, Status]
Index: []

In [52]:
df[df["Oil_Rate"].between(700 , 1200)]  #700 and 1200 included

  Well   Area Category  Oil_Rate  Water_Cut  Deferment_Hours  MTTR   Status
0   W1  South        A      1200         20                5   2.5   Online
1   W2  South        B       950         35               12   6.0  Offline
2   W3  North        A      1100         25                3   1.5   Online
4   W5   East        B       700         45               15   8.0   Online
7   W8  North        B       850         40                9   5.5   Online